### ISSUE TITLE
Create basic starter app

### ISSUE THREAD

**Issue by mikewheaton** [vitorleonel/reactpeople#1]
Get a basic app up and running that we can build off of.

**Comment by mikewheaton** [comment]
@vitorleonel How do you feel about starting with [create-react-app](https://github.com/facebook/create-react-app)? That provides a build system without configuration and we can always customize it later if necessary.

Also, do you want to use TypeScript for this project?

**Comment by vitorleonel** [comment]
@mikewheaton yes, we can use the create-react-app. In the initial stage I do not think of using typescript, my experience is small.

**Comment by mikewheaton** [comment]
Okay, let's use create-react-app with the default settings (no TypeScript). I'll assign this to myself and get an initial commit in soon.

**Comment by vitorleonel** [comment]
Nice!

**Comment by mikewheaton** [comment]
Thanks, I'll have a pull request in soon for this. 😄
