### ISSUE TITLE
Authentication window doesn't close

### ISSUE THREAD

**Issue by mikewheaton** [vitorleonel/reactpeople#10]
Repro steps:
1. Click the GitHub icon in the top right corner.
2. Pop up window opens.
3. Grant GitHub the permissions needed.

Instead of the pop up window closing and the app reflecting that I'm signed in, the pop up window stays open but shows the app:
![image](https://user-images.githubusercontent.com/1382445/47973004-6fa9ac00-e056-11e8-9935-9b2fe1b7a45c.png)

**Comment by vitorleonel** [comment]
@mikewheaton bug as fixed. Test and return feedback, please?

**Comment by mikewheaton** [comment]
Much better! There is no longer a popup and I'm redirected back to the main application after logging in. I'll close this issue.
