### ISSUE TITLE
Indicate user's logged-in status

### ISSUE THREAD

**Issue by mikewheaton** [vitorleonel/reactpeople#13]
**Current**
Before and after logging in, the same UI is shown:
![image](https://user-images.githubusercontent.com/1382445/48318222-ad0bbd80-e5b1-11e8-8023-486ae68767b4.png)

**Suggestion**
Display a string like 'Sign in with GitHub' when the user is signed out. Once they are signed in, display their GitHub username and/or avatar to indicate that they are signed in. Possibly include a 'sign out' link.

**Comment by vitorleonel** [comment]
Okay. It's valid suggestion.

**Comment by vitorleonel** [comment]
@mikewheaton your suggestion was applied!
